dotfiles_dir = ".dotfiles"

[settings]
prehooks = [ "notify-send \"Updating dots\""]
posthooks = ["chmod +x ~/.config/scripts/spam_click.py"]

[settings.dots]
fastfetch = {source = "fastfetch", target = ".config/fastfetch"}
fish = {source = "fish", target = ".config/fish"}
gitconfig = {source = "git/gitconfig", target = ".gitconfig"}
nvim = {source = "nvim", target = ".config/nvim"}
starship = {source = "starship.toml", target = ".config/starship.toml"}
yazi = {source = "yazi", target = ".config/yazi"}
bombadil = {source = "bombadil.toml", target = ".config/bombadil.toml"}
bombadil_vars = {source = "bombadil", target = ".config/bombadil"}
scripts = {source = "scripts", target = ".config/scripts"}

[profiles.desktop]
vars = ["bombadil/desktop_vars.toml"]

[profiles.desktop.dots]
dunst = {source = "dunst", target = ".config/dunst"}
hyprland = {source = "hyprland", target = ".config/hypr"}
kitty = {source = "kitty", target = ".config/kitty"}
rofi = {source = "rofi", target = ".config/rofi"}
wezterm = {source = "wezterm", target = ".config/wezterm"}
quickshell = {source = "quickshell", target = ".config/quickshell"}


[profiles.laptop]
vars = ["bombadil/laptop_vars.toml"]

[profiles.laptop.dots]
dunst = {source = "dunst", target = ".config/dunst"}
hyprland = {source = "hyprland", target = ".config/hypr"}
kitty = {source = "kitty", target = ".config/kitty"}
rofi = {source = "rofi", target = ".config/rofi"}
wezterm = {source = "wezterm", target = ".config/wezterm"}
quickshell = {source = "quickshell", target = ".config/quickshell"}

[profiles.catppuccin_mocha]
vars = ["bombadil/catppuccin_mocha.toml"]
