[colors]
bg_dark         = "#11111b" # Crust
bg_main         = "#1e1e2e" # Base
bg_panel        = "#181825" # Mantle
bg_surface      = "#313244" # Surface0
bg_float        = "#45475a" # Surface1
bg_selection    = "#585b70" # Surface2

fg_main         = "#cdd6f4" # Text
fg_soft         = "#bac2de" # Subtext1
fg_dim          = "#a6adc8" # Subtext0
fg_ghost        = "#6c7086" # Overlay0
fg_inverse      = "#11111b" # Crust (Text on bright backgrounds)

primary         = "#cba6f7" # Mauve
secondary       = "#f5c2e7" # Pink
tertiary        = "#89dceb" # Sky

success         = "#a6e3a1" # Green
warning         = "#f9e2af" # Yellow
error           = "#f38ba8" # Red
info            = "#89b4fa" # Blue
hint            = "#94e2d5" # Teal
urgent          = "#fab387" # Peach (Orange)

black           = "#45475a" # Surface1
red             = "#f38ba8" # Red
green           = "#a6e3a1" # Green
yellow          = "#f9e2af" # Yellow
blue            = "#89b4fa" # Blue
magenta         = "#cba6f7" # Mauve
cyan            = "#94e2d5" # Teal
white           = "#bac2de" # Subtext1

border_active   = "#cba6f7" # Mauve
border_inactive = "#313244" # Surface0
separator       = "#45475a" # Surface1
